export const API_PRODUCT_ACTION = "API_PRODUCT_ACTION";
export const API_PRODUCT_SUCCESS = "API_PRODUCT_SUCCESS";
export const API_PRODUCT_FAIL = "API_PRODUCT_FAIL";

export const API_COLORS_ACTION = "API_COLORS_ACTION";
export const API_COLORS_SUCCESS = "API_COLORS_SUCCESS";
export const API_COLORS_FAIL = "API_COLORS_FAIL";